### PR TITLE
docs: update branch changes in README

### PR DESCRIPTION
**Pull request by raszi**

### CODE REVIEW

**Comment by coorasse** [comment]
This PR would bring conflicts when we merge develop into master....if we are following gitflow...I don't knwo... @Senjai ?

**Comment by raszi** [comment]
Right now the main page has broken references.

As right now according to [this link](http://stackoverflow.com/a/18677732/221213) it is not possible to use the branch name in the README, so either the conflicts or the broken references.

**Comment by Senjai** [comment]
I do want to switch to using the master branch. The decision to use develop was made before I was involved. The problem is that the existing PR's against develop cannot be retargeted so I'd have to keep them in sync for a while after anyway.

**Comment by Senjai** [comment]
I do want to switch to using the master branch. The decision to use develop was made before I was involved. The problem is that the existing PR's against develop cannot be retargeted so I'd have to keep them in sync for a while after anyway.

**Comment by Senjai** [comment]
I do want to switch to using the master branch. The decision to use develop was made before I was involved. The problem is that the existing PR's against develop cannot be retargeted so I'd have to keep them in sync for a while after anyway.

**Pull request closed without merging**
