### PR TITLE
Changes Rule initialize method to take the more common &block style

### PR DESCRIPTION
**Pull request by phaedryx**
References:
https://github.com/ryanb/cancan/blob/2.0/lib/cancan/ability.rb#L109
https://github.com/ryanb/cancan/blob/2.0/lib/cancan/rule.rb#L13

### CODE REVIEW

**Comment by phaedryx** [comment]
Note: This is a small first step towards: https://github.com/CanCanCommunity/cancancan/issues/420

**Comment by coorasse** [comment]
could you please rebase on branch feature/3.0.0 and work on that one? Thanks

**Comment by phaedryx** [comment]
@coorasse will do. What's the time frame for a 3.0.0 release?

**Comment by coorasse** [comment]
We have nothing planned before a possible 3.0.0 release. This would be a sufficient feature to directly release as soon as it's ready. If is backward compatible (as I imagine it to be) we can release it as a minor upgrade as well

**Pull request closed without merging**
