### PR TITLE
[Solved] list user abilities - duplicate for merge

### PR DESCRIPTION
**Pull request by devaroop**
Created a method called 'permissions' which lists what a user can and cannot do. Ready for merge.

### CODE REVIEW

**Comment by devaroop** [comment]
This is a duplicate of #208 because I was having squashing problems. Refactored the code as per comments on #208 .

**Comment by nazartaran** [comment]
Hey, everyone, when that stuff will be merged ?

**Comment by Senjai** [comment]
@nazartaran I'll get it in tonight. There is an issue with pry as a development dependency with ruby 1.8, which causes the build failure. I'll have to fix that before this goes in.

**Comment by nazartaran** [comment]
@Senjai let me know please when you do your job, ty

**Comment by dsounded** [comment]
@Senjai what goes around with it ?

**Comment by Senjai** [comment]
@devaroop Thanks!

**Comment by dsounded** [comment]
@devaroop @Senjai  ty, dudes

**Pull request merged**
