### PR TITLE
Backport "Use `ActiveSupport.on_load` hook to include `CanCan::ModelAdditions`"

### LINKED ISSUE #405: cancancan breaks spring + rspec on rails 3.2.x
I'm having a problem running "springified" rspec on a rails 3.2.22.5 app, and through a process of elimination I isolated the problem to the cancancan gem.

This is the error I'm getting when running rspec with the app already preloaded with spring:
```
Failure/Error: DatabaseCleaner.clean_with(:truncation)

ActiveRecord::StatementInvalid:
  PG::ConnectionBad: PQsocket() can't get socket descriptor:           SELECT tablename
            FROM pg_tables
            WHERE schemaname = ANY (current_schemas(false))
```

I've setup a sample app running with docker compose to run the test in a reproduceable way:

https://github.com/IcaliaLabs/cancancan-test (Follow instructions on readme)

### PR DESCRIPTION
**Pull request by vovimayhem**
# What does this PR do?

- Backports #292 into the `develop` branch for a 1.x release [Closes #405]

### CODE REVIEW

**Comment by coorasse** [comment]
I pointed to the 1.x release. please recheck your PR and fix the CI. Thank you.

**Comment by vovimayhem** [comment]
OH OK! Cool :) Let me check that error...

**Comment by vovimayhem** [comment]
@coorasse The support for support Rails 3.2.x was also dropped from 1.x?

**Comment by coorasse** [comment]
At this point, it makes no sense to me to keep maintaining version 1.x since we are moving towards version 3.0. Thank you

**Pull request closed without merging**
