### PR TITLE
Drop old Rubies and update RuboCop

### PR DESCRIPTION
**Pull request by AlexWayfer**
Fix (and disable) new offenses.

Ruby 2.3 EOL was 31 months ago. We even don't test with them.

### CODE REVIEW

**Review by coorasse — APPROVED** [review]
Thanks!

**Comment by AlexWayfer** [comment]
I don't understand why actions are cancelled again…

**Comment by coorasse** [comment]
can you please rebase this PR?

**Comment by AlexWayfer** [comment]
@coorasse sorry, I've overlooked a notification about your request. I see you've already done a lot of changes like these and I'm glad to see them. I'll publish a new (fresh) PR if something will be wrong.

**Pull request closed without merging**
