### PR TITLE
    Extract resource-loading logic from ControllerResource into another class.

### PR DESCRIPTION
**Pull request by jcoglan**
I was reading the source of `ControllerResource` to try to understand why an `authorize_resource` macro in our controller was authorizing a different resource than the one we expected. I found it quite hard to see what was going on, because all the logic for `load_resource` is mixed into the same class as that for `authorize_resource`.

This commit extracts all the loading logic into a new class called `ControllerResource::Loader`, and refactors some internal APIs in the process to support the interaction between `Loader` and `ControllerResource`. These refactorings include:
- Extracing values that are a matter of definition (e.g. the options to `before_filter` and the lists of types of actions) into named constants.
- Pulling some repeated expressions into their own methods, e.g. `controller_action` and `collection_name`.
- Inlining some methods that are only called from one place, e.g. `initial_attributes`, `id_param_key`, `resource_class_with_parent`, `params_methods`, `namespace`.
- Eliminate some overly long expressions, and reduce complexity of a few methods by flattening conditional blocks.
- Using `__send__` rather than `send` to avoid accidentally calling user-defined domain methods called `send`.

### CODE REVIEW

**Comment by jcoglan** [comment]
I'm not sure why all these merge commits are in this PR, I only intended for my own commit to be here.

**Comment by jcoglan** [comment]
Never mind, I rebased it on top of `develop` and it looks okay now.

**Comment by Yoshyn** [comment]
:+1:

**Comment by coorasse** [comment]
please rebase on `feature/v2` branch

**Comment by coorasse** [comment]
I think this was a nicely done work but we have too many conflicts with the current version.
A new refactoring of the current develop branch would be more then welcome. I'll close this PR. Thank you

**Pull request closed without merging**
