### PR TITLE
Suppress deprecation warnings for Rails 4.2

### LINKED ISSUE #152: Deprecated sanitize_sql
This considered deprecated since Rails 4.2 and will be removed for 5.0
https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/model_adapters/active_record_adapter.rb#L120 Just reporting, sorry don't have much time to work on it.

### PR DESCRIPTION
**Pull request by marshall-lee**
This one adds activerecord_4.2 appraise and some fixes to suppress deprecation warnings.

fixes #152

### CODE REVIEW

**Comment by kelvinst** [comment]
Waiting for this too! Thanks for the hard work... (:

**Comment by JuanitoFatas** [comment]
Awesome @marshall-lee! :+1: :blush:

**Comment by bryanrite** [comment]
I'll get this merged in asap along with the travis fixes. Thanks guys.

**Comment by bryanrite** [comment]
Closing this in favour of #160 as I had to rebase.

**Comment by marshall-lee** [comment]
Thanks!

**Pull request closed without merging**
