### PR TITLE
Drop support for Rails < 4.2

### PR DESCRIPTION
**Pull request by oliverklee**
According to http://guides.rubyonrails.org/maintenance_policy.html , Rails
3.2, 4.0 and 4.1 have reached their end of life (as Rails 5.0 has been
released).  So we stop supporting it, allowing for faster builds on Travis,
code removal and simpler code.

### CODE REVIEW

**Comment by tarunjadhwani** [comment]
So cancancan works fine with rails 5, right?

**Comment by oliverklee** [comment]
I don't know. I haven't tested it yet (manually), there's still issue #286 for this, and the Rails 5 builds are still excluded from the build matrix: https://github.com/CanCanCommunity/cancancan/blob/develop/.travis.yml#L22

It looks like some Rails 5 work was done recently, though.

**Comment by Senjai** [comment]
Thank you for this. I'll be including it in the next major.

**Comment by coorasse** [comment]
I think is time for this to be merged. 
Maintenance for Rails 3.2 has been dropped now.
I would start a cancancan 2.0 version with this merged.

**Pull request merged**
