### PR TITLE
Fixes #139.

### LINKED ISSUE #139: load_and_authorize_resource doesn't assign attributes for update action
Even though the docs suggest that this is so. The strong parameters section even mentions that it checks for an update_params method.

### PR DESCRIPTION
**Pull request by kevintyll**
Used the tests by @rywall to fix attribute assignment bug in update action.

### CODE REVIEW

**Comment by jhawthorn** [comment]
:-1: I believe this was working as intended. Your application code should be responsible for performing the update. `load_and_authorize_resource` should only load and authorize.

Where in the docs did it suggest otherwise? We should fix that.

**Comment by rywall** [comment]
It suggests this in the Strong Params section of the docs: https://github.com/CanCanCommunity/cancancan#strong-parameters

It also works this way in the create action, further adding to the confusion.

**Comment by kevintyll** [comment]
Correct, the authorization was happening on updates without loading the form data, so I still had to manually load and authorize the object manually in the update actions.  Since the docs stated it should use strong params to load the object before authorizing per the link rywall provided, I went ahead and implemented that functionality.

**Comment by Senjai** [comment]
@rywall @kevintyll Thank you for your report but I agree with @jhawthorn that `find_resource` should never modify the resource it finds. The reason attributes are assigned in the create action is because it's considered a new action. 

The attributes are assigned in this case as a convenience as any attributes on the model at that time would be sourced from the form. When updating, unless you inspect the changed attributes, a found resource would appear to have values that would not be persisted along with others that may be persisted which can be problematic.

I assume that you have a situation like the following:

```ruby
  can :update, Thing, something: true
```

Which would fail authorization unless the value something is set to true before the authorization check is called. If you must handle this situation, I don't think CanCan should infer this for you. 

This is a hint that you might be able to architect your application a little more robustly. It makes no sense to allow this to happen when additional logic may eventually set it to something else. It only makes sense if `something: true` is persisted **before** the update is called.

**Comment by rywall** [comment]
Maybe I'm missing something but the strong parameters section of the README clearly suggests it will assign the attributes...

> By default, CanCan will try to sanitize the input on :create and **:update** routes by seeing if your controller will respond to the following methods

Am I misinterpreting the README?

**Comment by riffraff** [comment]
I second what @rywall the wiki page also says 

> If you specify a create_params or update_params method, CanCan will run that method depending on the action you are performing.

but `update_params` will in fact not be called in any way, AFAICT, so that probably also needs updating.

**Comment by Senjai** [comment]
@riffraff Would you be willing to make a pull request to the fact?

**Comment by riffraff** [comment]
not sure if this is ok, but if it is, I'll also update the wiki.

**Comment by sintro** [comment]
The readme is really incorrect in update_params description section. Suggested in PR read is better anyway.

**Pull request closed without merging**
