### PR TITLE
We must assign resource_instance before asking the controlller for resource_params

### PR DESCRIPTION
**Pull request by dima4p**
Sometimes (as in my case) the controller calculates the list of allowed fields in resource_params based on the current_user abilities. The latter needs the resource to be instantiated. But it turned out that it is not done for new_actions.
The commit fixes the situation.

### CODE REVIEW

**Comment by Senjai** [comment]
@dima4p Can you please provide a regression spec demonstrating where this fails as well as the fix?

**Comment by dima4p** [comment]
All the problems were in spec files that are fixed now. ;-)

**Comment by Senjai** [comment]
@dima4p closing this, as I understand that this is no longer an issue right? Let me know if I'm mistaken.

**Comment by dima4p** [comment]
Yes, you are mistaken. The bug remains as you did not merge the pull request.

**Pull request closed without merging**
