### PR TITLE
if/unless options for rules

### PR DESCRIPTION
**Pull request by fabn**
As requested in #105 here's my attempt to implement that.

See #105 for discussion and usage.

### CODE REVIEW

**Comment by fabn** [comment]
@bryanrite any hope to get this merged? Thanks.

**Comment by bryanrite** [comment]
Hi @fabn 

Sorry for taking so long on this, been busy :confused: 

I like the feature, the only reason I haven't merged it yet, is that it, along with a couple other PRs, like #192, are attempting to add context to rules but in a way that is not consistent with the way that other rules are added. Your additions would not work (and shouldn't) for collection style routes, but is written like a scope that could and I don't think that is obvious for some... and I would like the rules for an authorization framework to be unambiguous.

This is of course not your fault, but a limitation of the `ability` file, and you've implemented it really the only way you can.  I think we should have the ability to do `if`, `unless`, and `not`, along with controlling parameters sanitization, etc. so I am trying to redesign a DSL for the ability file to be unambiguous as well as more flexible when it comes to defining rules... which would include the functionality you've written here.

**Comment by fabn** [comment]
@bryanrite thanks for the status update.

**Comment by Senjai** [comment]
Hi @fabn,

I think this takes a good step towards the concept of using scopes instead of hash conditions, but I don't think the value is worth the complexity at the moment.

Currently, users can wrap can declarations in if blocks to solve the same problem and we don't have to support any additional code for this and we don't have to add an additional step in the matches_conditions method which is currently feeling some pain.

**Pull request closed without merging**
