### PR TITLE
Add Ruby 3.0 for CI

### PR DESCRIPTION
**Pull request by AlexWayfer**
Avoid incompatible RoR versions.

### CODE REVIEW

**Review by coorasse — APPROVED** [review]

**Comment by AlexWayfer** [comment]
Why jobs were canceled? 😓

**Comment by coorasse** [comment]
Ruby 3 incompatible with Rails 4 and 5 so we need to exclude them from the tests matrix. can you please take care of it and also rebase? Thanks! 🙏

**Comment by AlexWayfer** [comment]
> Ruby 3 incompatible with Rails 4 and 5 so we need to exclude them from the tests matrix. can you please take care of it and also rebase? Thanks! pray

Yep, of course, just waited for CI runs to figure out specific failing combinations.

**Comment by Liberatys** [comment]
@coorasse is this good to go? :D

**Review by coorasse — APPROVED** [review]

**Pull request merged**
