### PR TITLE
[WIP] Support STI

### PR DESCRIPTION
**Pull request by coorasse**

### CODE REVIEW

**Comment by meacuna** [comment]
Should we consider supporting multi-level STI? 
By taking a look at [`lib/cancan/ability.rb:305`](https://github.com/CanCanCommunity/cancancan/pull/578/files#diff-d4e0a70d43eb4c389e623945f417d6e0R305) I think subclasses' subclasses will not be considered.
Using `subject.descendants` instead of `subject.subclasses` should fix this.

**Comment by 23tux** [comment]
Whats the status of this issue? I'd be great if CanCanCan would support STIs

**Comment by coorasse** [comment]
No updates so far, this is a work that needs some time. I cannot make any promise on when I will be able to finish it. Please feel free to take over if you'd like.

**Comment by coorasse** [comment]
closed in favour of #649

**Pull request closed without merging**
