### PR TITLE
@_cancan_skipper should be inherited: add failing test

### PR DESCRIPTION
**Pull request by jpmckinney**
If a superclass controller has:

```
load_and_authorize_resource
skip_load_resource :only => :index
```

A subclass will not skip the loading of the resource on the `index` action.

I've added a failing test to illustrate this behavior.

Potential fix would be to use `class_attribute` from Rails: http://apidock.com/rails/Class/class_attribute

Moved from https://github.com/ryanb/cancan/pull/683

### CODE REVIEW

**Comment by coorasse** [comment]
@jpmckinney would you be up to fix this and send a PR?

**Comment by jpmckinney** [comment]
@coorasse When running `bundle exec rake spec` on a clean `develop` branch, I get a lot of errors, because ActiveSupport isn't loaded?

**Comment by coorasse** [comment]
check the `Development` section of the README: https://github.com/CanCanCommunity/cancancan#development

cancancan uses Appraisals

**Comment by jpmckinney** [comment]
@coorasse Thanks! I think my new commit will get the failing test passing.

**Comment by coorasse** [comment]
The CI is still failing. Fix it and then we can schedule this PR for the next version

**Comment by jpmckinney** [comment]
@coorasse They look like Rubocop failures for which I'm not responsible (I didn't touch those files).

**Comment by jpmckinney** [comment]
Ahhh, nevermind, I see what I did.

**Pull request merged**
